services:
  web:
    build:
      context: .
      dockerfile: ./docker_config/web.dockerfile
    ports:
      - 80:8080
    x-develop:
      watch:
        - path: web/
          target: /app
          action: sync